name: Vacancy_bot workflow

on: [push]

jobs:
  build_and_push_bot_to_docker_hub:
    name: Pushing bot image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./bot
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vacancy-bot:v1.0

  deploy:
    if: ${{ github.ref }} == 'main'
    runs-on: ubuntu-latest
    needs: build_and_push_bot_to_docker_hub
    steps:
      - name: pull docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/vacancy-bot:v1.0
            sudo docker-compose stop
            sudo docker-compose rm vacancy_bot

      - name: docker-compose up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd infra/
            sudo touch .env    
            touch .env

            sudo echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
            sudo echo CHAT_ID=${{ secrets.CHAT_ID }} >> .env
            sudo echo PAYMENTS=${{ secrets.PAYMENTS }} >> .env
            sudo echo LINK=${{ secrets.LINK }} >> .env
            
            sudo docker-compose up -d
            sudo docker system prune -f
