name: Vacancy_bot workflow

on: [push]

jobs:
  build_and_push_bot_to_docker_hub:
    name: Pushing bot image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vacancy-bot:v1.0

  on:
    push:
      branches:
        - main

  jobs:
    deploy:
      runs-on: ubuntu-latest
      needs:
        - build_and_push_bot_to_docker_hub

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Executing remote ssh commands to deploy
          run: |
            ssh ${{ secrets.USER }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -i ${{ secrets.SSH_KEY }} << 'EOF'
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/vacancy-bot:v1.0
            sudo docker-compose stop
            sudo docker-compose rm vacancy_bot

            touch .env

            echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
            echo CHAT_ID=${{ secrets.CHAT_ID }} >> .env
            echo PAYMENTS=${{ secrets.PAYMENTS }} >> .env
            echo LINK=${{ secrets.LINK }} >> .env

            sudo docker-compose up -d
            sudo docker system prune -f
            EOF