name: Vacancy_bot workflow

on: [push]

jobs:
  build_and_push_backend_to_docker_hub:
    name: Pushing backend image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vacancy-bot:v1.0

  deploy:
    name: Deploying on remote server
    runs-on: ubuntu-latest
    needs:
      - build_and_push_backend_to_docker_hub

    steps:
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/vacancy-bot:v1.0
            sudo docker-compose stop
            sudo docker-compose rm vacancy_bot

            rm .env
            touch .env

            sudo echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
            sudo echo CHAT_ID=${{ secrets.CHAT_ID }} >> .env
            sudo echo PAYMENTS=${{ secrets.PAYMENTS }} >> .env
            sudo echo LINK=${{ secrets.LINK }} >> .env

            sudo docker-compose up -d
            sudo docker system prune -f
